export enum Socials {
  INSTAGRAM = 'INSTAGRAM',
  VK = 'VK',
  FACEBOOK = 'FACEBOOK',
  LINKEDIN = 'LINKEDIN',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  SNAPCHAT = 'SNAPCHAT',
  TELEGRAM = 'TELEGRAM',
  STEAM = 'STEAM',
  SPOTIFY = 'SPOTIFY',
  DUOLINGO = 'DUOLINGO',
  TWITCH = 'TWITCH',
}
